### ISSUE TITLE
Merge projects

### ISSUE THREAD

**Issue by eugene-eeo** [nneonneo/fixedint#1]
Hey, I've gone through the fixedint codebase and I've recently come up with a (hopefully) refactored version. I think it is more straightforward, and I'd appreciate it if you could spend some time looking at the (very small) codebase.

https://github.com/eugene-eeo/fixedinteger

**Comment by nneonneo** [comment]
Thanks! The design goals for these projects is very different. My fixedint project aims to be more of a generic bitvector design, and I also did it partially to see what was involved in making a Python package. Your project is interesting and quite simple indeed - thanks for linking!
