### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by seanlaw** [nneonneo/fixedint#6]
@nneonneo I was trying to port some bit-shifting Java code over to Python and found out (the hard way) that Python does not have fixed width integers like Java. Your package saved me a tonne of time and, from one [open source creator](https://github.com/TDAmeritrade/stumpy) to another, I just wanted to drop you a note to say "Thank You" and have a wonderful day!

[Please feel free to close this]

**Comment by nneonneo** [comment]
Thanks for the kind words! I am happy that this package was useful to someone :)
